### ISSUE TITLE
Failed to find a suitable GPU!

### ISSUE THREAD

**Issue by Nv7-GitHub** [moazzamak/vulkan-template#2]
I compiled it with `cmake .` and `make`. I changed line 971 on `VulkanizedEngine.hpp` to 
```cpp
VkExtent2D actualExtent = {(uint32_t)width, (uint32_t)height};
```
because it wasn't compiling. After this, running `make` succeeded. But when I ran it, I got the error
```
Failed to find a suitable GPU!
```
Is there a way to fix this?

**Comment by moazzamak** [comment]
Hi,
This is a pretty old project and I haven't tried to run it in a long time. It's possible the issue you're having is related to drivers, so maybe you should check that.
Could you create a pull request for any issues you fixed so that people who use this code in the future can get it working out of the box? That would be much appreciated. Thanks

**Comment by Nv7-GitHub** [comment]
I was able to get it to work by getting rid of the if statement here: https://github.com/moazzamak/vulkan-template/blob/c1a3bf6c7055047b026bdb78e3d17847800bf484/VulkanizedEngine.hpp#L653 and just assuming that the device worked. After this, I was able to get it working!

![Screenshot](https://cdn.discordapp.com/attachments/814906806563635242/841378000242737202/unknown.png)

**Comment by moazzamak** [comment]
Could you post your OS and hardware setup? It might help understand what's happening.
I couldn't replicate any of the issues you mentioned and everything worked out of the box for me.

Gonna leave this issue open for a while to see if someone else is getting it as well.

**Comment by Nv7-GitHub** [comment]
OS: MacOS Big Sur (11.3)
CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
GPU (Integrated Graphics): Intel Iris Pro 1536 MB
